### ISSUE TITLE
Remove address parameter

### ISSUE THREAD

**Issue by evilrobot-01** [tellor-io/tellor-pallet#48]
The [`address`](https://github.com/tellor-io/tellor-pallet/blob/5a9aee1b1a0cc15e6155ba0a086b9828ee083a79/src/lib.rs#L1341) parameter of the `report_stake_withdrawn` function is currently not being used. Can it be removed, or should it be used to double-check against the address on locally registered staker details?

**Comment by oraclown** [comment]
Thanks for spotting this. I think it can be removed, since one EVM-compatible address will be linked to one oracle consumer parachain account, and the address is already being passed to the oracle consumer parachain when `reportStakeWithdrawn` is called on the controller contracts side.

Contracts change documented here: [#40](https://github.com/tellor-io/tellor-parachain-contracts/issues/40)
